USE [master]
GO

/****** Object:  Database [warsztat]    Script Date: 2014-08-10 02:11:43 ******/
CREATE DATABASE [warsztat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'warsztat', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\warsztat.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'warsztat_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\warsztat_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [warsztat] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [warsztat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [warsztat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [warsztat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [warsztat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [warsztat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [warsztat] SET ARITHABORT OFF 
GO

ALTER DATABASE [warsztat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [warsztat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [warsztat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [warsztat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [warsztat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [warsztat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [warsztat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [warsztat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [warsztat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [warsztat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [warsztat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [warsztat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [warsztat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [warsztat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [warsztat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [warsztat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [warsztat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [warsztat] SET RECOVERY FULL 
GO

ALTER DATABASE [warsztat] SET  MULTI_USER 
GO

ALTER DATABASE [warsztat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [warsztat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [warsztat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [warsztat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [warsztat] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [warsztat] SET  READ_WRITE 
GO

